"""Register user use case for user registration with default title."""

from typing import Optional

from ...domain.repositories.user_repository import IUserRepository
from ...domain.repositories.settings_repository import ISettingsRepository
from ...domain.entities.user import User
from ...domain.value_objects.title import Title
from ...domain.value_objects.timezone import Timezone
from ...domain.exceptions import UserNotFoundError


class RegisterUserUseCase:
    """Use case for registering a new user with default title."""

    def __init__(
        self,
        user_repository: IUserRepository,
        settings_repository: ISettingsRepository,
    ):
        """
        Initialize register user use case.
        
        Args:
            user_repository: User repository interface
            settings_repository: Settings repository interface
        """
        self._user_repository = user_repository
        self._settings_repository = settings_repository

    async def execute(
        self,
        telegram_user_id: int,
        telegram_username: Optional[str] = None,
        display_name: Optional[str] = None,
    ) -> bool:
        """
        Execute user registration use case.
        
        Args:
            telegram_user_id: Telegram user ID (must be > 0)
            telegram_username: Telegram username (optional)
            display_name: Display name from Telegram (optional)
            
        Returns:
            True if user was created, False if user already existed (idempotent)
            
        Raises:
            ValueError: If telegram_user_id is invalid
            ConnectionError: If database connection fails
        """
        # Validate inputs
        if telegram_user_id <= 0:
            raise ValueError("Invalid telegram_user_id: must be > 0")
        
        # Check if user already exists (idempotent)
        existing_user = await self._user_repository.get_by_telegram_id(telegram_user_id)
        if existing_user:
            return False  # User already exists, return success (idempotent)
        
        # Get default title from settings
        default_title_str = await self._settings_repository.get_default_title()
        default_title = Title(default_title_str if default_title_str else "")
        
        # Create new user
        # Note: id, created_at, and updated_at are auto-generated by the database
        user = User(
            telegram_user_id=telegram_user_id,
            telegram_username=telegram_username,
            display_name=display_name,
            full_title=default_title,  # Set default title as full_title
            title=Title(""),  # Displayed title starts empty (will be calculated from full_title on first percentage message)
            title_letter_count=0,
            title_locked=False,
            timezone=Timezone.default(),  # Default to UTC
            language="en",  # Default to English
            last_percentage=None,
            last_processed_date=None,
            # id, created_at, and updated_at are set by database
        )
        
        # Save user to repository
        try:
            await self._user_repository.save(user)
            return True  # User created successfully
        except Exception as e:
            # Handle database errors
            if "connection" in str(e).lower() or "network" in str(e).lower():
                raise ConnectionError(f"Database connection failed: {str(e)}")
            raise  # Re-raise other exceptions
